UI/ux daily challange
txj0925/2024_S1_-W102-_Star-Clicker pull request #12
Opened 2024-05-29 04:30 UTC by giangh00

2024-05-30 02:15 UTC, txj0925 requested changes
It does not seem to work. All challenges have 0 reward and we can all claim them.
If we press on the button to claim we don't get anything. Also the first challenge is not set.

2024-06-04 03:27 UTC, jyb4913 approved these changes
ok

2024-06-04 03:28 UTC, jyb4913 approved these changes
OK

2024-06-04 03:31 UTC, txj0925 approved these changes

2024-06-04 03:31 UTC, merged